# Generated by Django 6.0.7 on 2026-07-24 06:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groq_api_key', models.CharField(blank=True, default='', help_text='Secret key from console.groq.com. Required for every AI feature — menu planning, product recommendations, supplier/farmer insights, and the in-app assistant. Leave blank to disable AI features.', max_length=200)),
                ('groq_model', models.CharField(default='llama-3.3-70b-versatile', help_text='Groq model id used for all AI calls (e.g. llama-3.3-70b-versatile).', max_length=100)),
                ('groq_timeout_seconds', models.PositiveIntegerField(default=30, help_text='How long to wait for a Groq response before treating the call as failed.')),
                ('platform_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Service fee applied to every produce order placed through the platform, as a percentage (e.g. 8.00 = 8%).', max_digits=5)),
                ('support_email', models.EmailField(blank=True, default='hello@sokopulse.co.ke', help_text='Shown to users and used as the reply-to for system notifications.', max_length=254)),
                ('site_name', models.CharField(default='SokoPulse', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System configuration',
                'verbose_name_plural': 'System configuration',
            },
        ),
    ]
