# Generated by Django 6.0.7 on 2026-07-24 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='payments_enabled',
            field=models.BooleanField(default=False, help_text='When ON, the premium actions below require an active subscription. When OFF, every account can use the full platform for free — no payment modal is ever shown.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='subscription_period_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days a subscription payment covers.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='subscription_price_farmer',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Monthly subscription price (KSh) for farmer accounts.', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='subscription_price_institution',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Monthly subscription price (KSh) for institution accounts.', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='subscription_price_supplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('2500.00'), help_text='Monthly subscription price (KSh) for supplier accounts.', max_digits=10),
        ),
    ]
