# Generated by Django 6.0.7 on 2026-07-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
