# Generated by Django 6.0.7 on 2026-07-25 16:25

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.AdminAwareUserManager()),
            ],
        ),
    ]
