# Generated by Django 6.0.6 on 2026-07-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('category', models.CharField(choices=[('grain', 'Grain / Staple'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('legume', 'Legume'), ('fat', 'Fat / Oil'), ('other', 'Other')], default='other', max_length=20)),
                ('calories_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein_g_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs_g_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat_g_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contains_meat', models.BooleanField(default=False)),
                ('contains_dairy', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('portion_size', models.CharField(blank=True, help_text='e.g. 1 plate, 350g', max_length=100)),
                ('prep_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_portion', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='nutrition.RecipeIngredient', to='nutrition.ingredient'),
        ),
    ]
