# Generated by Django 6.0.6 on 2026-07-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Created by the AI weekly-menu generator rather than the curated recipe library.'),
        ),
    ]
