# Generated by Django 6.0.6 on 2026-07-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='nutrition.ingredient')),
                ('source_menu_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_signals', to='menus.menuplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('crop_focus', models.CharField(blank=True, help_text='e.g. Cabbage, Tomatoes', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_committed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='farmers.demandsignal')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='farmers.farmer')),
            ],
        ),
    ]
