# Generated by Django 6.0.6 on 2026-07-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('ordered', 'Ordered')], default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nutrient_summary', models.JSONField(blank=True, default=dict)),
                ('generation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plans', to='institutions.institution')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('institution', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_slot', models.CharField(max_length=20)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='nutrition.recipe')),
                ('menu_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menuplan')),
            ],
            options={
                'ordering': ['day', 'meal_slot'],
            },
        ),
    ]
