# Generated by Django 6.0.6 on 2026-07-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuplan',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Natural-language summary returned by the AI when this plan was generated.'),
        ),
        migrations.AddField(
            model_name='menuplan',
            name='selected_ingredient_ids',
            field=models.JSONField(blank=True, default=list, help_text='Ingredient IDs the menu was constrained to build from (AI/manual flows).'),
        ),
        migrations.AddField(
            model_name='menuplan',
            name='source',
            field=models.CharField(choices=[('heuristic', 'Automatic (heuristic engine)'), ('ai_auto', 'AI-recommended products'), ('ai_manual', 'AI menu from manually chosen products')], default='heuristic', max_length=20),
        ),
    ]
