# Generated by Django 6.0.7 on 2026-07-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuplan_ai_summary_menuplan_selected_ingredient_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuplan',
            name='duplicated_from',
            field=models.ForeignKey(blank=True, help_text="Set when this plan was created by reusing another week's menu rather than generated fresh — e.g. repeating the same weekly rotation across a termly billing cycle.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='menus.menuplan'),
        ),
    ]
