# Generated by Django 6.0.7 on 2026-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
