# Generated by Django 6.0.7 on 2026-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_produceorder_is_paid_produceorder_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
