# Generated by Django 6.0.6 on 2026-07-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('canteen', 'Canteen')], default='school', max_length=20)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('budget_per_meal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('target_calories', models.PositiveIntegerField(default=2000, help_text='kcal / person / day')),
                ('target_protein_g', models.PositiveIntegerField(default=50)),
                ('target_carbs_g', models.PositiveIntegerField(default=260)),
                ('target_fat_g', models.PositiveIntegerField(default=65)),
                ('guideline_reference', models.CharField(blank=True, max_length=255)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_profile', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='institutions.institution')),
            ],
        ),
    ]
