# Generated by Django 6.0.7 on 2026-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='budget_breakfast',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Budget per learner/patient for breakfast (KSh). Leave blank if this institution doesn't offer breakfast.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='budget_lunch',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Budget per learner/patient for lunch (KSh). Leave blank if this institution doesn't offer lunch.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='budget_supper',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Budget per learner/patient for supper (KSh). Leave blank if this institution doesn't offer supper.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='budget_per_meal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Overall fallback budget per meal (KSh). Auto-derived from the breakfast/lunch/supper budgets below when at least one of them is set; used by the menu engine for any meal slot that doesn't have its own budget.", max_digits=10),
        ),
    ]
