# Generated by Django 6.0.7 on 2026-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_budget_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('termly', 'Termly (3 months)')], default='weekly', help_text='How often this institution charges/budgets for meals — e.g. a canteen billing individuals monthly, or a boarding school charging per school term.', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='budget_mode',
            field=models.CharField(choices=[('per_meal', 'Split by meal (breakfast / lunch / supper)'), ('total_per_cycle', 'One total amount for the whole billing cycle')], default='per_meal', help_text='Whether the budget below is split per meal (breakfast/lunch/supper) or given as one total figure per person for the whole billing cycle.', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='budget_total_per_cycle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Only used when budget_mode is 'total_per_cycle': the total meal budget per learner/patient/staff member for one whole billing cycle (e.g. per term, per month).", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='budget_per_meal',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Overall fallback budget per meal (KSh). Auto-derived from the breakfast/lunch/supper budgets, or from budget_total_per_cycle, depending on budget_mode; used by the menu engine for any meal slot that doesn't have its own budget.", max_digits=10),
        ),
    ]
